# Generated by Django 3.2 on 2021-09-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('later', '0002_user_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reading_list',
            field=models.JSONField(null=True),
        ),
    ]
